### ISSUE TITLE
Error in CLI tool without arguments in dockerized version

### ISSUE THREAD

**Issue by alvarosainzpardo** [telefonicaid/fiware-device-simulator#49]
I have just installed the dockerized version of the simulator. When I execute de CLI tool, without arguments, I get this error:

```
root@7c60a8ea4ad4:/opt/fiware-device-simulator# ./bin/fiwareDeviceSimulatorCLI
/opt/fiware-device-simulator/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js:5
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/opt/fiware-device-simulator/node_modules/request/node_modules/hawk/lib/index.js:5:33)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
root@7c60a8ea4ad4:/opt/fiware-device-simulator#
```

**Comment by fgalan** [comment]
This issue could be fixed (or alliviated) by PR https://github.com/telefonicaid/fiware-device-simulator/pull/47. Pending to check.
