### ISSUE TITLE
Node v10 migration issues

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-device-simulator#55]
It seems that a problem with eval 0.1.2 module is precluding fiware-device-simulator unit test to work fine with Node v10.

In particular, we are getting errors 22 errors, most one like this one:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "options.filename" property must be of type string. Received type object
    at new Script (vm.js:62:13)
    at module.exports (node_modules/eval/eval.js:72:18)
    at Object.collect (lib/collectors/fiwareDeviceSimulatorCollector.js:38:12)
    at Context.<anonymous> (test/unit/collectors/fiwareDeviceCollector_test.js:33:22)
```

If we hack the eval.js 0.1.2 code this way:

```
$ diff -u node_modules/eval/eval.js node_modules/eval/eval.js.orig
--- node_modules/eval/eval.js	2018-11-14 11:32:15.258076938 +0100
+++ node_modules/eval/eval.js.orig	2018-11-14 11:32:10.362076780 +0100
@@ -57,10 +57,6 @@
     filename: filename,
     displayErrors: false
   }
-  if (options.filename == null)
-  {
-    options.filename = '';
-  }
 
   if (isBuffer(content)) {
     content = content.toString()
``` 

The all test pass ok.

Looking to eval git repository it seems, the following PR https://github.com/pierrec/node-eval/pull/17 will fix the problem (it seems to be a kind of "clean version" of my hack).

**Comment by fgalan** [comment]
Interesting article about eval: https://odino.org/eval-no-more-understanding-vm-vm2-nodejs, which conclude that we shouldn't be using eval module.

**Comment by fgalan** [comment]
https://github.com/pierrec/node-eval/pull/17 was merged at the end and a new version of the eval package (0.1.3) released in the npm registry with the fix.

Fixed by PR https://github.com/telefonicaid/fiware-device-simulator/pull/64, upgrading packages.json to use the new version.
